name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [main]  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run build -- --base-href /physiofirst/

      - uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
